# This file contains Home Assistant sensor entities.
# Define sensors here, including template sensors, REST sensors, and platform-specific sensors.
# Sensors provide data from various sources like weather APIs, system stats, or calculated values.
#
# Example sensor configuration (commented out):
#
# - platform: template
#   sensors:
#     example_temperature:
#       friendly_name: "Example Temperature"
#       value_template: "{{ states('sensor.raw_temp') | float | round(1) }}"
#       unit_of_measurement: "°C"
#       device_class: temperature
#       icon_template: mdi:thermometer

# Automation Count Sensors
- platform: template
  sensors:
    automation_count:
      friendly_name: "Total Automations"
      value_template: "{{ states.automation | list | length }}"
      icon_template: mdi:robot
      unit_of_measurement: "automations"
    
    automation_enabled_count:
      friendly_name: "Enabled Automations"
      value_template: "{{ states.automation | selectattr('state', 'eq', 'on') | list | length }}"
      icon_template: mdi:check-circle
      unit_of_measurement: "automations"
    
    automation_disabled_count:
      friendly_name: "Disabled Automations"
      value_template: "{{ states.automation | selectattr('state', 'eq', 'off') | list | length }}"
      icon_template: mdi:cancel
      unit_of_measurement: "automations"

    script_count:
      friendly_name: "Total Scripts"
      value_template: "{{ states.script | list | length }}"
      icon_template: mdi:script-text
      unit_of_measurement: "scripts"

    sensor_count:
      friendly_name: "Total Sensors"
      value_template: "{{ states.sensor | list | length }}"
      icon_template: mdi:eye
      unit_of_measurement: "sensors"
