# This workflow runs on your self-hosted runner and deploys docker-compose and config files to your Docker host.
# It assumes your runner has access to the correct directories and Docker.

name: Deploy Docker Compose Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy updated stack
        run: |
          cd /home/docker/homeassistant
          cp $GITHUB_WORKSPACE/docker-compose.yml ./
          cp $GITHUB_WORKSPACE/homeassistant/configuration.yaml ./homeassistant/configuration.yaml
          cp $GITHUB_WORKSPACE/mosquitto/mosquitto.conf ./mosquitto/mosquitto.conf
          docker-compose up -d
        shell: bash

      - name: Verify deployment
        run: docker-compose ps
        shell: bash
